CREATE TABLE T_TRACE_CHATROOMS (
  ChatRoomID NUMBER PRIMARY KEY,
  CreatorID NUMBER REFERENCES T_TRACE_USERS(UserID),
  RoomName VARCHAR2(100),
  CreatedAt TIMESTAMP DEFAULT SYSDATE
);
CREATE SEQUENCE T_TRACE_CHATROOMS_SEQ START WITH 1 INCREMENT BY 1;


CREATE TABLE T_TRACE_CHAT_PARTICIPANTS (
  ChatRoomID NUMBER REFERENCES T_TRACE_CHATROOMS(ChatRoomID),
  UserID NUMBER REFERENCES T_TRACE_USERS(UserID),
  IsActive CHAR(1) DEFAULT 'Y',
  PRIMARY KEY (ChatRoomID, UserID)
);



CREATE TABLE T_TRACE_CHAT_MESSAGES (
  MessageID NUMBER PRIMARY KEY,
  ChatRoomID NUMBER REFERENCES T_TRACE_CHATROOMS(ChatRoomID),
  SenderID NUMBER REFERENCES T_TRACE_USERS(UserID),
  Content VARCHAR2(1000),
  SentAt TIMESTAMP DEFAULT SYSDATE
);
CREATE SEQUENCE T_TRACE_CHAT_MESSAGES_SEQ START WITH 1 INCREMENT BY 1;


-- 채팅방 생성
INSERT INTO T_TRACE_CHATROOMS 
(ChatRoomID, CreatorID, RoomName) 
VALUES (T_TRACE_CHATROOMS_SEQ.NEXTVAL, 1, 'Min x Sunny');

-- 참여자 추가
INSERT INTO T_TRACE_CHAT_PARTICIPANTS (ChatRoomID, UserID) VALUES (1, 1);
INSERT INTO T_TRACE_CHAT_PARTICIPANTS (ChatRoomID, UserID) VALUES (1, 23);

select * from T_TRACE_CHAT_MESSAGES;

INSERT INTO T_TRACE_CHAT_MESSAGES 
(MessageID, ChatRoomID, SenderID, Content) 
VALUES (T_TRACE_CHAT_MESSAGES_SEQ.NEXTVAL, 1, 1, '안녕 Sunny!');
