-- 커뮤니티 테이블 생성
CREATE TABLE T_TRACE_COMMUNITIES (
    COMMUNITY_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    CREATED_AT DATE DEFAULT SYSDATE
);

-- 시퀀스 생성
CREATE SEQUENCE T_TRACE_COMMUNITIES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

INSERT INTO T_TRACE_COMMUNITIES (COMMUNITY_ID, NAME, DESCRIPTION)
VALUES (T_TRACE_COMMUNITIES_SEQ.NEXTVAL, '스포츠 소통방', '스포츠 팬들을 위한 커뮤니티');

INSERT INTO T_TRACE_COMMUNITIES (COMMUNITY_ID, NAME, DESCRIPTION)
VALUES (T_TRACE_COMMUNITIES_SEQ.NEXTVAL, '테크놀로지 탐험', '최신 기술과 디바이스 이야기');
