--DROP TABLE T_TRACE_CHATROOMS;
--DROP TABLE T_TRACE_CHAT_PARTICIPANTS;
--DROP TABLE T_TRACE_CHAT_MESSAGES;

--DROP SEQUENCE T_TRACE_CHATROOMS_SEQ;
--DROP SEQUENCE T_TRACE_CHAT_MESSAGES_SEQ;


CREATE TABLE T_TRACE_CHATROOMS (
  ChatRoomID NUMBER PRIMARY KEY,
  CreatorID NUMBER REFERENCES T_USER(USERID),
  RoomName VARCHAR2(100),
  CreatedAt TIMESTAMP DEFAULT SYSDATE
);
CREATE SEQUENCE T_TRACE_CHATROOMS_SEQ START WITH 1 INCREMENT BY 1;



CREATE TABLE T_TRACE_CHAT_PARTICIPANTS (
  ChatRoomID NUMBER REFERENCES T_TRACE_CHATROOMS(ChatRoomID),
  UserID NUMBER REFERENCES T_USER(USERID),
  IsActive CHAR(1) DEFAULT 'Y',
  PRIMARY KEY (ChatRoomID, UserID)
);



CREATE TABLE T_TRACE_CHAT_MESSAGES (
  MessageID NUMBER PRIMARY KEY,
  ChatRoomID NUMBER REFERENCES T_TRACE_CHATROOMS(ChatRoomID),
  SenderID NUMBER REFERENCES T_USER(USERID),
  Content VARCHAR2(1000),
  SentAt TIMESTAMP DEFAULT SYSDATE
);
CREATE SEQUENCE T_TRACE_CHAT_MESSAGES_SEQ START WITH 1 INCREMENT BY 1;

select * from T_TRACE_CHATROOMS;
select * from T_TRACE_CHAT_PARTICIPANTS;
select * from T_TRACE_CHAT_MESSAGES;



INSERT INTO T_TRACE_CHATROOMS (ChatRoomID, CreatorID, RoomName)
VALUES (T_TRACE_CHATROOMS_SEQ.NEXTVAL, 2, 'asdasd님과 Min님의 채팅방');

INSERT INTO T_TRACE_CHATROOMS (ChatRoomID, CreatorID, RoomName)
VALUES (T_TRACE_CHATROOMS_SEQ.NEXTVAL, 6, 'asdasd, Min, Sunny 그룹 채팅');

INSERT INTO T_TRACE_CHAT_PARTICIPANTS (ChatRoomID, UserID) VALUES (1, 2);
INSERT INTO T_TRACE_CHAT_PARTICIPANTS (ChatRoomID, UserID) VALUES (1, 6); -- Min

INSERT INTO T_TRACE_CHAT_PARTICIPANTS (ChatRoomID, UserID) VALUES (2, 2);
INSERT INTO T_TRACE_CHAT_PARTICIPANTS (ChatRoomID, UserID) VALUES (2, 6); -- Min
INSERT INTO T_TRACE_CHAT_PARTICIPANTS (ChatRoomID, UserID) VALUES (2, 7); -- Sunny


INSERT INTO T_TRACE_CHAT_MESSAGES (MessageID, ChatRoomID, SenderID, Content, SentAt)
VALUES (T_TRACE_CHAT_MESSAGES_SEQ.NEXTVAL, 1, 2, '안녕하세요, Min님!', SYSDATE - 1/24);

INSERT INTO T_TRACE_CHAT_MESSAGES (MessageID, ChatRoomID, SenderID, Content, SentAt)
VALUES (T_TRACE_CHAT_MESSAGES_SEQ.NEXTVAL, 1, 6, '안녕하세요, asdasd님.', SYSDATE - 1/24/60);

INSERT INTO T_TRACE_CHAT_MESSAGES (MessageID, ChatRoomID, SenderID, Content, SentAt)
VALUES (T_TRACE_CHAT_MESSAGES_SEQ.NEXTVAL, 2, 6, '그룹 채팅방에 오신 것을 환영합니다!', SYSDATE - 1/24/2);

INSERT INTO T_TRACE_CHAT_MESSAGES (MessageID, ChatRoomID, SenderID, Content, SentAt)
VALUES (T_TRACE_CHAT_MESSAGES_SEQ.NEXTVAL, 2, 2, '반갑습니다!', SYSDATE - 1/24/3);

INSERT INTO T_TRACE_CHAT_MESSAGES (MessageID, ChatRoomID, SenderID, Content, SentAt)
VALUES (T_TRACE_CHAT_MESSAGES_SEQ.NEXTVAL, 2, 7, '모두 좋은 하루 되세요~', SYSDATE - 1/24/4);