-- 외래 키가 있는 테이블부터 순서대로 삭제
--DROP TABLE T_TRACE_CHAT_MESSAGES;
--DROP TABLE T_TRACE_CHAT_PARTICIPANTS;
--DROP TABLE T_TRACE_CHATROOMS;

-- 시퀀스 삭제
--DROP SEQUENCE T_TRACE_CHATROOMS_SEQ;
--DROP SEQUENCE T_TRACE_CHAT_MESSAGES_SEQ;






CREATE TABLE T_TRACE_CHATROOMS (
  ChatRoomID NUMBER PRIMARY KEY,
  CreatorID VARCHAR2(255) REFERENCES T_USER(ID),
  RoomName VARCHAR2(100),
  CreatedAt TIMESTAMP DEFAULT SYSDATE
);
CREATE SEQUENCE T_TRACE_CHATROOMS_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE T_TRACE_CHAT_PARTICIPANTS (
  ChatRoomID NUMBER REFERENCES T_TRACE_CHATROOMS(ChatRoomID),
  UserID VARCHAR2(255) REFERENCES T_USER(ID),
  IsActive CHAR(1) DEFAULT 'Y',
  PRIMARY KEY (ChatRoomID, UserID)
);

CREATE TABLE T_TRACE_CHAT_MESSAGES (
  MessageID NUMBER PRIMARY KEY,
  ChatRoomID NUMBER REFERENCES T_TRACE_CHATROOMS(ChatRoomID),
  SenderID VARCHAR2(255) REFERENCES T_USER(ID),
  Content VARCHAR2(1000),
  SentAt TIMESTAMP DEFAULT SYSDATE
);
CREATE SEQUENCE T_TRACE_CHAT_MESSAGES_SEQ START WITH 1 INCREMENT BY 1;










-- T_USER 테이블의 ID 컬럼에서 가져온 값들 (예시)
-- 'gwegwe', 'test1', 'asdasd', 'jidang2024', 'ingyun8668', 'test', 'jipgagosipda', 'sunny', 'leo', 'mira', 'hyun'

INSERT INTO T_TRACE_CHATROOMS (ChatRoomID, CreatorID, RoomName)
VALUES (T_TRACE_CHATROOMS_SEQ.NEXTVAL, 'asdasd', 'asdasd님과 Min님의 채팅방');

INSERT INTO T_TRACE_CHATROOMS (ChatRoomID, CreatorID, RoomName)
VALUES (T_TRACE_CHATROOMS_SEQ.NEXTVAL, 'test', 'asdasd, Min, Sunny 그룹 채팅');

INSERT INTO T_TRACE_CHAT_PARTICIPANTS (ChatRoomID, UserID) VALUES (1, 'asdasd');
INSERT INTO T_TRACE_CHAT_PARTICIPANTS (ChatRoomID, UserID) VALUES (1, 'jipgagosipda'); -- Min

INSERT INTO T_TRACE_CHAT_PARTICIPANTS (ChatRoomID, UserID) VALUES (2, 'asdasd');
INSERT INTO T_TRACE_CHAT_PARTICIPANTS (ChatRoomID, UserID) VALUES (2, 'jipgagosipda'); -- Min
INSERT INTO T_TRACE_CHAT_PARTICIPANTS (ChatRoomID, UserID) VALUES (2, 'sunny'); -- Sunny

INSERT INTO T_TRACE_CHAT_MESSAGES (MessageID, ChatRoomID, SenderID, Content, SentAt)
VALUES (T_TRACE_CHAT_MESSAGES_SEQ.NEXTVAL, 1, 'asdasd', '안녕하세요, Min님!', SYSDATE - 1/24);

INSERT INTO T_TRACE_CHAT_MESSAGES (MessageID, ChatRoomID, SenderID, Content, SentAt)
VALUES (T_TRACE_CHAT_MESSAGES_SEQ.NEXTVAL, 1, 'jipgagosipda', '안녕하세요, asdasd님.', SYSDATE - 1/24/60);

INSERT INTO T_TRACE_CHAT_MESSAGES (MessageID, ChatRoomID, SenderID, Content, SentAt)
VALUES (T_TRACE_CHAT_MESSAGES_SEQ.NEXTVAL, 2, 'jipgagosipda', '그룹 채팅방에 오신 것을 환영합니다!', SYSDATE - 1/24/2);

INSERT INTO T_TRACE_CHAT_MESSAGES (MessageID, ChatRoomID, SenderID, Content, SentAt)
VALUES (T_TRACE_CHAT_MESSAGES_SEQ.NEXTVAL, 2, 'asdasd', '반갑습니다!', SYSDATE - 1/24/3);

INSERT INTO T_TRACE_CHAT_MESSAGES (MessageID, ChatRoomID, SenderID, Content, SentAt)
VALUES (T_TRACE_CHAT_MESSAGES_SEQ.NEXTVAL, 2, 'sunny', '모두 좋은 하루 되세요~', SYSDATE - 1/24/4);