spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=scoutprojecttester@gmail.com
spring.mail.password=myfsvrormibwyzdb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.reset.password.base-url=https://yourdomain.com/customer/resetPassword
