spring.mail.host=smtp.naver.com
spring.mail.port=587
spring.mail.username=your.email@naver.com
spring.mail.password=앱비밀번호

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.reset.password.base-url=https://yourdomain.com/customer/resetPassword
