CREATE TABLE TRAVEL_COURSE (
  COURSE_ID NUMBER PRIMARY KEY,
  TITLE VARCHAR2(200),
  DESCRIPTION CLOB,
  REGION_ID NUMBER REFERENCES REGION(REGION_ID),
  USER_ID NUMBER REFERENCES USERS(USER_ID),
  CREATED_AT DATE
);
CREATE SEQUENCE TRAVEL_COURSE_SEQ START WITH 1 INCREMENT BY 1;